[package]
name = "clap-test"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
serde = { version = "1.0.228" , features = ["derive"] }
toml = "0.7"
serde_json = "1.0.149"
chrono = "0.4"
thiserror = "2.0.17"
env_logger = "0.11.9"
log = "0.4.29"
